### ISSUE TITLE
Organogram revamp

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#362]
Assemble data:
* [x] Reconcile triplestore organizations
* [x] Compare existing data in organogram viz, triplestore & uploads page
* [x] Generate missing XLS files from triplestore data

Vizualization (CSV)
* [x] Viz code
* [ ] Test sample of existing records https://github.com/datagovuk/ckanext-dgu/issues/365
* [ ] Integrate into CKAN page https://github.com/datagovuk/ckanext-dgu/issues/366

Uploads process:
* [x] Design
* [x] Import existing data
* [ ] Implement design https://github.com/datagovuk/ckanext-dgu/issues/367
* [ ] Integration with CKAN https://github.com/datagovuk/ckanext-dgu/issues/369
* [ ] Test https://github.com/datagovuk/ckanext-dgu/issues/370
* [ ] Documentation https://github.com/datagovuk/ckanext-dgu/issues/371

Roll-out
* [ ] E2E tests (upload and browse vizualizations) - internal testers https://github.com/datagovuk/ckanext-dgu/issues/372
* [ ] E2E tests - external testers https://github.com/datagovuk/ckanext-dgu/issues/373
* [ ] Blog post https://github.com/datagovuk/ckanext-dgu/issues/374
* [ ] Email publishers with link to new guidance https://github.com/datagovuk/ckanext-dgu/issues/375

**Comment by davidread** [comment]
CC @ratajczak

**Comment by davidread** [comment]
Closing this, as I've split the remaining tasks into tickets.
